### ISSUE TITLE
The condensed distance matrix must contain only finite values

### ISSUE THREAD

**Issue by 1431206** [wma1995/TaphonomeAnalyst#1]
Hi, I encountered some problem running your script with presented data.
Using Visual Studio Code, got a message:
Traceback (most recent call last):
  File "D:\works\personal\learning\севин\apps\taphocen-analys\TaphonomeAnalyst.py", line 847, in <module>
    args.func(args)
  File "D:\works\personal\learning\севин\apps\taphocen-analys\TaphonomeAnalyst.py", line 55, in clusterenv
    mergings = linkage(otu_category_df_filter_standardscale, method='average', metric='braycurtis',
  File "C:\Users\33340\AppData\Local\Programs\Python\Python310\lib\site-packages\scipy\cluster\hierarchy.py", line 1065, in linkage
    raise ValueError("The condensed distance matrix must contain only "
ValueError: The condensed distance matrix must contain only finite values.
Maybe I displaced some starting parameters:
python TaphonomeAnalyst.py clusterenv --input Supplementary_table_1.xlsx --category family --aquatic AQUATIC  --output png

**Comment by wma1995** [comment]
Can you provide the data? I'll check what the problem is and follow up with improvements.
Email : wma19952022@163.com
